version: "3.8"

services:
  backend:
    build: .
    container_name: sharespace-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/sharespace
      - SENTIMENT_URL=http://sentiment:7000/predict
      - CONDITION_URL=http://condition:7001/predict_file
    depends_on:
      - mongo
      - sentiment
      - condition

  condition:
    build: ./Condition
    container_name: condition-ml
    ports:
      - "7001:7001"

  sentiment:
    build: ./Sentiment
    container_name: sentiment-ml
    ports:
      - "7000:7000"

  mongo:
    image: mongo:7
    container_name: sharespace-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
